export const colors = {
  primary: '#f17511',
  background: '#FDF0E6',//'#ebdbc1',
  white: '#ffffff',
  black: '#2f2621', 
  grey: '#aaaaaa',
  dark_grey: '#333333',
  progress_bar: '#7BC8CA',//'#f17511',
  red: '#C41E3A',
  ice: '#7BC8CA',
  light_grey: 'lightgrey',
  yellow: '#699da8',//'#F3BF5B',
  backgroundDark: '#0A0A0A',
  grey: '#8F8F8F',
  optionBackground: '#151515',
  optionBorder: '#333333',
  gold: '#FFDA47',
  separator: '#333333',
  selectedBackground: '#333333',
  green: '#00ab66',
  disabled: '#666666', 
  dark_tan: '#DFCDB9',
}

export const questions = [
  { id: 1, text: "Where are you from and what would you show people who came to visit?" },
  { id: 2, text: "What’s an interesting random fact you’ve learned online?" },
  { id: 3, text: "Would you rather have a free Monday or a free Friday?" },
  { id: 4, text: "What’s something funny that’s happened to you recently?" },
  { id: 5, text: "What's an interesting YouTube video or TikTok you’ve seen?" },
  { id: 6, text: "What’s a cool experience you’ve had?" },
  { id: 7, text: "What would your friends and family assume you had done if you were arrested without explanation?" },
  { id: 8, text: "What’s a dumb way you’ve ever hurt yourself?" },
  { id: 9, text: "What’s an interesting conspiracy theory you may or may not believe in?" },
  { id: 10, text: "If you could switch lives with any fictional character, who would it be?" },
  { id: 11, text: "What’s something you nerd out about?" },
  { id: 12, text: "What’s your dream job?" },
  { id: 13, text: "What skill do you want to learn or get better at?" },
  { id: 14, text: "What’s one thing you really want to do on your bucket list?" },
  { id: 15, text: "If you could meet any historical figure, who would it be and why?" },
  { id: 16, text: "What’s a good piece of advice you’ve heard?" },
  { id: 17, text: "What’s an adventurous thing you’ve ever done?" },
  { id: 18, text: "What’s a goal you’re currently working towards?" },
  { id: 19, text: "What’s a failure you’ve experienced that ended up teaching you something valuable?" },
  { id: 20, text: "What’s a mistake you’ve made that you still feel guilty about?" },
  { id: 21, text: "What’s a big risk you’ve ever taken, and how did it turn out?" },
  { id: 22, text: "What’s a red flag in dating?" },
  { id: 23, text: "What’s a personality trait you wish you could change about yourself?" },
  { id: 24, text: "Defend a hot take." },
  { id: 25, text: "If you could speak to one animal, which would you choose and why?" },
  { id: 26, text: "What’s the funniest thing you believed as a kid?" },
  { id: 27, text: "What’s an embarrassing thing that’s happened to you?" }
]