export const colors = {
  primary: '#f26422',
  black: '#0A0A0A',
  white: '#ffffff',
  grey: '#aaaaaa',
  dark_grey: '#333333',
  progress_bar: '#a37b73',
  red: '#C41E3A',
  ice: 'rgba(0, 115, 154, 1)',
  light_grey: 'lightgrey',
  yellow: '#F3BF5B',
  backgroundDark: '#0A0A0A',
  grey: '#B0B0B0',
  optionBackground: '#151515',
  optionBorder: '#333333',
  gold: '#FFDA47',
  separator: '#333333',
  selectedBackground: '#333333',
  green: '#00ab66',
  disabled: '#666666'
}

export const questions = [
    { id: 1, text: "What's your favorite hobby?" },
    { id: 2, text: "If you could travel anywhere, where would you go?" },
    { id: 3, text: "What's the last book you read?" },
    { id: 4, text: "Describe your perfect day." },
    { id: 5, text: "What's a skill you'd like to learn?" },
    { id: 6, text: "What's your favorite movie?" },
    { id: 7, text: "What's your favorite type of music?" },
    { id: 8, text: "Do you have any pets?" },
    { id: 9, text: "What's your favorite food?" },
    { id: 10, text: "What's your favorite season, and why?" },
    { id: 11, text: "What's your favorite way to relax?" },
    { id: 12, text: "What's your favorite sport to watch or play?" },
    { id: 13, text: "What's your favorite childhood memory?" },
    { id: 14, text: "If you could have dinner with anyone, living or dead, who would it be?" },
    { id: 15, text: "What's your favorite place in your hometown?" },
    { id: 16, text: "Do you prefer coffee or tea?" },
    { id: 17, text: "What's your favorite holiday?" },
    { id: 18, text: "What's your favorite TV show?" },
    { id: 19, text: "What's your favorite board game?" },
    { id: 20, text: "What's your favorite video game?" },
    { id: 21, text: "Do you have a favorite quote or saying?" },
    { id: 22, text: "What's your favorite animal?" },
    { id: 23, text: "What's your favorite dessert?" },
    { id: 24, text: "What's your favorite app on your phone?" },
    { id: 25, text: "What's your favorite way to exercise?" },
    { id: 26, text: "What's your favorite type of cuisine?" },
    { id: 27, text: "Do you prefer the beach or the mountains?" },
    { id: 28, text: "What's your favorite book genre?" },
    { id: 29, text: "What's your favorite flower?" },
    { id: 30, text: "What's your favorite ice cream flavor?" },
    { id: 31, text: "What's your favorite fruit?" },
    { id: 32, text: "What's your favorite vegetable?" },
    { id: 33, text: "What's your favorite drink?" },
    { id: 34, text: "What's your favorite candy?" },
    { id: 35, text: "What's your favorite snack?" },
    { id: 36, text: "What's your favorite fast food restaurant?" },
    { id: 37, text: "What's your favorite restaurant?" },
    { id: 38, text: "What's your favorite type of weather?" },
    { id: 39, text: "What's your favorite type of movie?" },
    { id: 40, text: "What's your favorite type of music to dance to?" },
    { id: 41, text: "What's your favorite type of art?" },
    { id: 42, text: "What's your favorite sport to watch?" },
    { id: 43, text: "What's your favorite sport to play?" },
    { id: 44, text: "What's your favorite outdoor activity?" },
    { id: 45, text: "What's your favorite indoor activity?" },
    { id: 46, text: "What's your favorite thing to do on weekends?" },
    { id: 47, text: "What's your favorite thing about your job?" },
    { id: 48, text: "What's your favorite thing to do with friends?" },
    { id: 49, text: "What's your favorite thing to do alone?" },
    { id: 50, text: "What's your favorite way to spend a rainy day?" },
    { id: 51, text: "What's your favorite thing to cook or bake?" },
    { id: 52, text: "What's your favorite holiday tradition?" },
    { id: 53, text: "What's your favorite childhood toy?" },
    { id: 54, text: "What's your favorite video streaming service?" },
    { id: 55, text: "What's your favorite social media platform?" },
    { id: 56, text: "What's your favorite thing about your favorite season?" },
    { id: 57, text: "What's your favorite thing to collect?" },
    { id: 58, text: "What's your favorite way to start your day?" },
    { id: 59, text: "What's your favorite way to end your day?" },
    { id: 60, text: "What's your favorite thing to wear?" },
    { id: 61, text: "What's your favorite scent?" },
    { id: 62, text: "What's your favorite type of cake?" },
    { id: 63, text: "What's your favorite thing about your city?" },
    { id: 64, text: "What's your favorite thing to do on vacation?" },
    { id: 65, text: "What's your favorite time of day?" },
    { id: 66, text: "What's your favorite type of cheese?" },
    { id: 67, text: "What's your favorite thing to do on a sunny day?" },
    { id: 68, text: "What's your favorite way to stay active?" },
    { id: 69, text: "What's your favorite thing to read besides books?" },
    { id: 70, text: "What's your favorite thing about nature?" },
    { id: 71, text: "What's your favorite thing to photograph?" },
    { id: 72, text: "What's your favorite thing about technology?" },
    { id: 73, text: "What's your favorite way to give back?" },
    { id: 74, text: "What's your favorite thing to watch on YouTube?" },
    { id: 75, text: "What's your favorite thing to do on a lazy day?" },
    { id: 76, text: "What's your favorite thing to decorate your home with?" },
    { id: 77, text: "What's your favorite kind of sandwich?" },
    { id: 78, text: "What's your favorite thing about your family?" },
    { id: 79, text: "What's your favorite thing to do during the holidays?" },
    { id: 80, text: "What's your favorite thing to write about?" },
    { id: 81, text: "What's your favorite type of workout?" },
    { id: 82, text: "What's your favorite thing about your culture?" },
    { id: 83, text: "What's your favorite game to play with friends?" },
    { id: 84, text: "What's your favorite thing to do at a party?" },
    { id: 85, text: "What's your favorite way to treat yourself?" },
    { id: 86, text: "What's your favorite thing to do in the morning?" },
    { id: 87, text: "What's your favorite thing to do in the evening?" },
    { id: 88, text: "What's your favorite thing to learn about?" },
    { id: 89, text: "What's your favorite type of pie?" },
    { id: 90, text: "What's your favorite thing to do at the beach?" },
    { id: 91, text: "What's your favorite thing to do in the snow?" },
    { id: 92, text: "What's your favorite kind of soup?" },
    { id: 93, text: "What's your favorite thing to do in a park?" },
    { id: 94, text: "What's your favorite thing to do in a movie theater?" },
    { id: 95, text: "What's your favorite thing to do on a road trip?" },
    { id: 96, text: "What's your favorite thing to do with your family?" },
    { id: 97, text: "What's your favorite thing to do with your significant other?" },
    { id: 98, text: "What's your favorite thing about yourself?" },
    { id: 99, text: "What's your favorite hobby to do on weekends?" },
    { id: 100, text: "What's your favorite thing to do on a night out?" },
    { id: 101, text: "What's your favorite thing to wear on a casual day?" },
    { id: 102, text: "What's your favorite thing to do on a date?" },
    { id: 103, text: "What's your favorite thing about your best friend?" },
    { id: 104, text: "What's your favorite thing to do during free time?" },
    { id: 105, text: "What's your favorite place to visit in your country?" },
    { id: 106, text: "What's your favorite type of movie genre?" },
    { id: 107, text: "What's your favorite hobby to do indoors?" },
    { id: 108, text: "What's your favorite hobby to do outdoors?" },
    { id: 109, text: "What's your favorite kind of music to listen to?" },
    { id: 110, text: "What's your favorite instrument to play?" },
    { id: 111, text: "What's your favorite song at the moment?" },
    { id: 112, text: "What's your favorite way to listen to music?" },
    { id: 113, text: "What's your favorite podcast?" },
    { id: 114, text: "What's your favorite radio station?" },
    { id: 115, text: "Who's your favorite singer or band?" },
    { id: 116, text: "What's your favorite album?" },
    { id: 117, text: "What's your favorite concert you've attended?" },
    { id: 118, text: "What's your favorite author?" },
    { id: 119, text: "What's your favorite book series?" },
    { id: 120, text: "What's your favorite story you've read?" },
    { id: 121, text: "Who's your favorite book character?" },
    { id: 122, text: "What's your favorite non-fiction book?" },
    { id: 123, text: "What's your favorite fiction book?" },
    { id: 124, text: "What's your favorite way to read books?" },
    { id: 125, text: "What's your favorite bookstore?" },
    { id: 126, text: "What's your favorite library you've visited?" },
    { id: 127, text: "What's your favorite e-book you own?" },
    { id: 128, text: "What's your favorite way to mark your books?" },
    { id: 129, text: "What's your favorite literary genre?" },
    { id: 130, text: "What's your favorite book you've written?" },
    { id: 131, text: "What's your favorite thing about reading?" },
    { id: 132, text: "What's your favorite book to recommend?" },
    { id: 133, text: "What's your favorite way to discuss books?" },
    { id: 134, text: "What's your favorite book that made you cry?" },
    { id: 135, text: "What's your favorite book that made you laugh?" },
    { id: 136, text: "What's your favorite book that inspired you?" },
    { id: 137, text: "What's your favorite book you've gifted?" },
    { id: 138, text: "What's your favorite book you've borrowed?" },
    { id: 139, text: "What's your favorite book you want to gift to someone?" },
    { id: 140, text: "What's your favorite book you own for your collection?" },
    { id: 141, text: "What's your favorite book you've read multiple times?" },
    { id: 142, text: "What's your favorite book you couldn't put down?" },
    { id: 143, text: "What's your favorite book that changed your perspective?" },
    { id: 144, text: "What's your favorite book that made you laugh out loud?" },
    { id: 145, text: "What's your favorite book that taught you something new?" },
    { id: 146, text: "What's your favorite book that you found challenging?" },
    { id: 147, text: "What's your favorite book that you found easy to read?" },
    { id: 148, text: "What's your favorite book with a great plot?" },
    { id: 149, text: "What's your favorite book with great characters?" },
    { id: 150, text: "What's your favorite book with great dialogue?" },
    { id: 151, text: "What's your favorite book with great descriptions?" },
    { id: 152, text: "What's your favorite book with a great cover?" },
    { id: 153, text: "What's your favorite book with an unexpected twist?" },
    { id: 154, text: "What's your favorite book with a happy ending?" },
    { id: 155, text: "What's your favorite book with a sad ending?" },
    { id: 156, text: "What's your favorite book with a surprising ending?" },
    { id: 157, text: "What's your favorite book with a complex storyline?" },
    { id: 158, text: "What's your favorite book with a simple storyline?" },
    { id: 159, text: "What's your favorite book with a strong moral?" },
    { id: 160, text: "What's your favorite book with a weak moral?" },
    { id: 161, text: "What's your favorite book with good pacing?" },
    { id: 162, text: "What's your favorite book with slow pacing?" },
    { id: 163, text: "What's your favorite book with fast pacing?" },
    { id: 164, text: "What's your favorite book with a unique narrative style?" },
    { id: 165, text: "What's your favorite book with multiple perspectives?" },
    { id: 166, text: "What's your favorite standalone novel?" },
    { id: 167, text: "What's your favorite book that's part of a series?" },
    { id: 168, text: "What's your favorite book adapted into a movie?" },
    { id: 169, text: "What's your favorite book not adapted into a movie?" },
    { id: 170, text: "What's your favorite book set in the future?" },
    { id: 171, text: "What's your favorite book set in the past?" },
    { id: 172, text: "What's your favorite book set in the present?" },
    { id: 173, text: "What's your favorite book set in an imaginary world?" },
    { id: 174, text: "What's your favorite book set in the real world?" },
    { id: 175, text: "What's your favorite book you couldn't live without?" },
    { id: 176, text: "What's your favorite way to stay organized?" },
    { id: 177, text: "What's your favorite productivity tool?" },
    { id: 178, text: "What's your favorite way to manage stress?" },
    { id: 179, text: "What's your favorite relaxation technique?" },
    { id: 180, text: "What's your favorite way to celebrate a success?" },
    { id: 181, text: "What's your favorite way to handle failure?" },
    { id: 182, text: "What's your favorite motivational quote?" },
    { id: 183, text: "What's your favorite way to stay motivated?" },
    { id: 184, text: "What's your favorite way to improve yourself?" },
    { id: 185, text: "What's your favorite personal development book?" },
    { id: 186, text: "What's your favorite way to set goals?" },
    { id: 187, text: "What's your favorite way to track your progress?" },
    { id: 188, text: "What's your favorite way to stay productive?" },
    { id: 189, text: "What's your favorite morning routine?" },
    { id: 190, text: "What's your favorite evening routine?" },
    { id: 191, text: "What's your favorite way to unwind after a long day?" },
    { id: 192, text: "What's your favorite way to spend time with loved ones?" },
    { id: 193, text: "What's your favorite way to explore new interests?" },
    { id: 194, text: "What's your favorite way to challenge yourself?" },
    { id: 195, text: "What's your favorite way to feel accomplished?" },
    { id: 196, text: "What's your favorite way to stay positive?" },
    { id: 197, text: "What's your favorite way to enjoy life?" },
    { id: 198, text: "What's your favorite way to have fun with friends?" },
    { id: 199, text: "What's your favorite way to enjoy your family?" },
    { id: 200, text: "What's your favorite way to enjoy your alone time?" },
    { id: 201, text: "What's your favorite way to enjoy nature?" },
    { id: 202, text: "What's your favorite way to enjoy the outdoors?" },
    { id: 203, text: "What's your favorite way to enjoy the indoors?" },
    { id: 204, text: "What's your favorite way to enjoy your hobbies?" },
    { id: 205, text: "What's your favorite way to enjoy your interests?" },
    { id: 206, text: "What's your favorite way to enjoy your passions?" },
    { id: 207, text: "What's your favorite way to enjoy your day?" },
    { id: 208, text: "What's your favorite way to enjoy your night?" },
    { id: 209, text: "What's your favorite way to enjoy your morning?" },
    { id: 210, text: "What's your favorite way to enjoy your evening?" },
    { id: 211, text: "What's your favorite way to enjoy your weekend?" },
    { id: 212, text: "What's your favorite way to enjoy your vacation?" },
    { id: 213, text: "What's your favorite way to enjoy your work?" },
    { id: 214, text: "What's your favorite way to enjoy your study time?" },
    { id: 215, text: "What's your favorite way to enjoy your leisure time?" },
    { id: 216, text: "What's your favorite way to enjoy your free time?" },
    { id: 217, text: "What's your favorite way to enjoy your time off?" },
    { id: 218, text: "What's your favorite way to enjoy your life?" },
    { id: 219, text: "What's your favorite way to enjoy your day off?" },
    { id: 220, text: "What's your favorite way to enjoy your break?" },
    { id: 221, text: "What's your favorite way to enjoy time with friends?" },
    { id: 222, text: "What's your favorite way to enjoy time with family?" },
    { id: 223, text: "What's your favorite way to enjoy time alone?" },
    { id: 224, text: "What's your favorite way to enjoy time outdoors?" },
    { id: 225, text: "What's your favorite way to enjoy time indoors?" },
    { id: 226, text: "What's your favorite way to enjoy your hobbies?" },
    { id: 227, text: "What's your favorite way to enjoy your interests?" },
    { id: 228, text: "What's your favorite way to enjoy your passions?" },
    { id: 229, text: "What's your favorite way to enjoy your day?" },
    { id: 230, text: "What's your favorite way to enjoy your night?" },
    { id: 231, text: "What's your favorite way to enjoy your morning?" },
    { id: 232, text: "What's your favorite way to enjoy your evening?" },
    { id: 233, text: "What's your favorite way to enjoy your weekend?" },
    { id: 234, text: "What's your favorite way to enjoy your vacation?" },
    { id: 235, text: "What's your favorite way to enjoy your work?" },
    { id: 236, text: "What's your favorite way to enjoy your study time?" },
    { id: 237, text: "What's your favorite way to enjoy your leisure time?" },
    { id: 238, text: "What's your favorite way to enjoy your free time?" },
    { id: 239, text: "What's your favorite way to enjoy your time off?" },
    { id: 240, text: "What's your favorite way to enjoy your life?" },
    { id: 241, text: "What's your favorite way to enjoy your day off?" },
    { id: 242, text: "What's your favorite way to enjoy your break?" },
    { id: 243, text: "What's your favorite way to enjoy time with friends?" },
    { id: 244, text: "What's your favorite way to enjoy time with family?" },
    { id: 245, text: "What's your favorite way to enjoy time alone?" },
    { id: 246, text: "What's your favorite way to enjoy time outdoors?" },
    { id: 247, text: "What's your favorite way to enjoy time indoors?" },
    { id: 248, text: "What's your favorite way to enjoy your hobbies?" },
    { id: 249, text: "What's your favorite way to enjoy your interests?" },
    { id: 250, text: "What's your favorite way to enjoy your passions?" },
    { id: 251, text: "What's your favorite way to learn something new?" },
    { id: 252, text: "What's your favorite way to stay informed?" },
    { id: 253, text: "What's your favorite way to spend a Sunday?" },
    { id: 254, text: "What's your favorite way to spend a Monday?" },
    { id: 255, text: "What's your favorite way to spend a Tuesday?" },
    { id: 256, text: "What's your favorite way to spend a Wednesday?" },
    { id: 257, text: "What's your favorite way to spend a Thursday?" },
    { id: 258, text: "What's your favorite way to spend a Friday?" },
    { id: 259, text: "What's your favorite way to spend a Saturday?" },
    { id: 260, text: "What's your favorite memory from the past year?" },
    { id: 261, text: "What's your favorite thing to do during summer?" },
    { id: 262, text: "What's your favorite thing to do during winter?" },
    { id: 263, text: "What's your favorite thing to do during spring?" },
    { id: 264, text: "What's your favorite thing to do during fall?" },
    { id: 265, text: "What's your favorite way to stay connected with friends?" },
    { id: 266, text: "What's your favorite way to stay connected with family?" },
    { id: 267, text: "What's your favorite way to meet new people?" },
    { id: 268, text: "What's your favorite way to make new friends?" },
    { id: 269, text: "What's your favorite way to maintain friendships?" },
    { id: 270, text: "What's your favorite way to celebrate your birthday?" },
    { id: 271, text: "What's your favorite birthday memory?" },
    { id: 272, text: "What's your favorite way to decorate for a party?" },
    { id: 273, text: "What's your favorite type of party?" },
    { id: 274, text: "What's your favorite thing to do at a festival?" },
    { id: 275, text: "What's your favorite thing to do at a fair?" },
    { id: 276, text: "What's your favorite thing to do at a carnival?" },
    { id: 277, text: "What's your favorite thing to do at a picnic?" },
    { id: 278, text: "What's your favorite thing to do at a barbecue?" },
    { id: 279, text: "What's your favorite thing to do at a wedding?" },
    { id: 280, text: "What's your favorite thing to do at a graduation?" },
    { id: 281, text: "What's your favorite thing to do at a reunion?" },
    { id: 282, text: "What's your favorite thing to do during a long weekend?" },
    { id: 283, text: "What's your favorite thing to do when you have free time?" },
    { id: 284, text: "What's your favorite thing to do to stay entertained?" },
    { id: 285, text: "What's your favorite way to challenge yourself intellectually?" },
    { id: 286, text: "What's your favorite way to challenge yourself physically?" },
    { id: 287, text: "What's your favorite way to express creativity?" },
    { id: 288, text: "What's your favorite way to show appreciation?" },
    { id: 289, text: "What's your favorite way to give compliments?" },
    { id: 290, text: "What's your favorite way to receive compliments?" },
    { id: 291, text: "What's your favorite way to handle criticism?" },
    { id: 292, text: "What's your favorite way to stay humble?" },
    { id: 293, text: "What's your favorite way to practice gratitude?" },
    { id: 294, text: "What's your favorite way to stay motivated during tough times?" },
    { id: 295, text: "What's your favorite way to celebrate achievements?" },
    { id: 296, text: "What's your favorite way to help others?" },
    { id: 297, text: "What's your favorite way to learn new skills?" },
    { id: 298, text: "What's your favorite way to teach others?" },
    { id: 299, text: "What's your favorite way to spend quality time?" },
    { id: 300, text: "What's the best piece of advice you've ever received?" },
  ];